name: expense_tracker
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  animate_do: ^3.3.4
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  babstrap_settings_screen: ^0.1.6
  path: ^1.9.0
  intl: any
  flutter_slidable: ^3.1.0
  flutter_form_builder: ^9.2.1
  cupertino_onboarding: ^1.2.0
  rflutter_alert: ^2.0.7
  bottom_picker: ^2.4.0
  flutter_initicon: ^3.0.0+1
  flex_color_scheme: ^7.3.1
  fl_chart: ^0.66.2
  sliding_clipped_nav_bar: ^3.1.1
  accordion: ^2.6.0
  isar: ^3.1.0+1
  path_provider: ^2.1.2
  isar_flutter_libs: ^3.1.0+1
  material_color_utilities: ^0.8.0
  random_color_scheme: ^0.1.4
  graphic: ^2.2.1
  animated_conditional_builder: ^0.0.5
  dropdown_textfield: ^1.0.8
  widget_circular_animator: ^1.0.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: 
  build_runner:
  analyzer: 
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
# Icon Lunacher App
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_launcher/expenses.png"
  web:
    generate: true
    image_path: "assets/icon_launcher/expenses.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon_launcher/expenses.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon_launcher/expenses.png"
  linux:
    generate: true
    image_path: "assets/icon_launcher/expenses.png"
  # Icon Lunacher App  
# Splash Screen
flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_image/1.png
  branding: assets/splash_image/1.png
  color_dark: "#121212"
  image_dark: assets/splash_image/1.png
  branding_dark: assets/splash_image/1.png

  android_12:
    image: assets/splash_image/1.png
    icon_background_color: "#ffffff"
    image_dark: assets/splash_image/1.png
    icon_background_color_dark: "#121212"

  web: true
# Splash Screen
flutter:
  uses-material-design: true
  assets:
    - assets/lang/ar.json
    - assets/lang/en.json

  fonts:
  - family: Cairo
    fonts:
    - asset: assets/fonts/cairo/Cairo.ttf

  - family: Rubik
    fonts:
    - asset: assets/fonts/rubik/Rubik.ttf

